# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
source 'https://github.com/Deadknight/dk-specs.git'
source 'https://cdn.cocoapods.org/'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'Topping', '0.1.3'

  target 'iosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosAppUITests' do
    # Pods for testing
  end

end
