source 'https://github.com/Deadknight/dk-specs.git'
source 'https://github.com/CocoaPods/Specs'

target 'iosApp' do
  use_frameworks!
  platform :ios, '11.0'
  
  pod 'shared', :path => '../shared'
  pod 'Topping', '0.1.6'
  pod 'Toaster', '2.3.0'
  pod 'GDataXML-HTML', '~> 1.4.1'
  pod 'ActionSheetPicker-3.0'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'MaterialComponents/BottomAppBar', '119.5.0'
  pod 'MaterialComponents/ActivityIndicator', '119.5.0'
  pod 'MDFInternationalization', '2.0.0'
  
end
