source 'https://github.com/Deadknight/dk-specs.git'
source 'https://github.com/CocoaPods/Specs'

use_frameworks!

platform :ios, '11.0'

target 'iosApp' do
  pod 'shared', :path => '../shared'
  pod 'Topping', '0.5.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
    end
    target.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end
